# Resources/config/services.yaml
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Golpilolz\DBConfigs\Service\:
    resource: '../'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'